language: java
jdk:
  - oraclejdk8
# language: node_js
# node_js:
#   - '6'
#   - '5'
#   - '4'
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
install:
  - nvm install 6
  - npm install
before_script:
  - npm install -g bower polymer-cli firebase-tools
  - bower install
  # - polymer lint
script:
  - xvfb-run polymer test
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test --plugin sauce --skip-plugin local; fi
