language: java
jdk:
  - oraclejdk8
dist: trusty
sudo: required
addons:
  sauce_connect: true
install:
  - nvm install 6
  - npm install
before_script:
  - npm install -g bower polymer-cli
  - bower install
  # - polymer lint
script:
  - polymer test --plugin sauce --skip-plugin local
after_success:
  - npm install -g firebase-tools
  - polymer build
  - firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
  #- if [ "${TRAVIS_BRANCH}" = "master" ]; then echo Deploying master; else echo Skipping Deploy; fi
