language: java
jdk:
  - oraclejdk8
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
install:
  - nvm install 6
  - npm install
before_script:
  - npm install -g bower polymer-cli
  - bower install
  # - polymer lint
script:
  #- xvfb-run polymer test
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test --plugin sauce --skip-plugin local; fi
after_success:
  - npm install -g firebase-tools
  - firebase deploy --token=${FIREBASE_API_KEY}
  #- if [ "${TRAVIS_BRANCH}" = "master" ]; then echo Deploying master; else echo Skipping Deploy; fi
