sudo: required
dist: trusty
addons:
  firefox: '46.0'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '6'
  - '5'
  - '4'
before_install:
  - sudo apt-get -y install openjdk-8-jdk
before_script:
  - npm install -g bower polymer-cli firebase-tools
  - bower install
script:
  - xvfb-run polymer test
